version: "3"
services:
    client:
        build: ./client/       
        restart: always        
        ports:            
        - "80:3000"        
        volumes:            
        - ./client:/client/src/app            
        links:            
            - backend
        networks:            
            - webappnetwork
    backend:        
        build: ./backend/       
        restart: always       
        ports:            
            - "5000:5000"        
        volumes:            
            - ./backend:/backend               
        networks:            
            - webappnetwork
networks:    
    webappnetwork:        
        driver: bridge

