version: "3"
services:
    client:
        build: .        
        restart: always        
        ports:            
        - "3000:3000"        
        volumes:            
        - ./client:/client/src/app            
        links:            
            - backend
        networks:            
            - webappnetwork
    backend:        
        build: .       
        restart: always       
        ports:            
            - "5000:5000"        
        volumes:            
            - ./backend:/backend           
        depends_on:            
            - mongodb       
        networks:            
            - webappnetwork
    mongodb:        
        image: mongo        
        restart: always        
        container_name: mongodb          
        command: mongod --noauth         
        networks:            
            - webappnetwork
networks:    
    webappnetwork:        
        driver: bridge

