version: "3"
services:
    client:
        container_name: docker-frontend
        build: ./client
        restart: always
        ports: 
        - '80:3000'
        depends_on:
        - backend
        networks:            
        - webappnetwork
    backend:        
        container_name: docker-backend
        build: ./backend
        restart: always
        ports: 
        - '5000:5000'
        links:
        - mongo     
        networks:            
        - webappnetwork
    mongo:   
        container_name: mongo
        image: mongo
        restart: always
        ports: 
        - '27017:27017'     
networks:    
    webappnetwork:        
        driver: bridge